apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: teampensjon
  name: pensjon-kodeverk
  namespace: teampensjon
spec:
  port: 8080
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  ingresses:
    - https://pensjon-kodeverk.intern.dev.nav.no