apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjondeployer
  name: pensjon-kodeverk
  namespace: pensjondeployer
spec:
  port: 8080
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  ingresses:
    - https://pensjon-kodeverk.intern.nav.no