apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: pensjondeployer
  name: pensjon-kodeverk
  namespace: pensjondeployer
spec:
  port: 8080
  accessPolicy:
    inbound:
      rules:
        - application: pen-nks-service
          namespace: pensjon-saksbehandling
          cluster: prod-fss
        - application: pen-nks-service
          namespace: pensjon-saksbehandling
          cluster: prod-gcp
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-psak
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-pselv
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-pselv
          namespace: pensjondeployer
          cluster: prod-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  ingresses:
    - https://pensjon-kodeverk.intern.nav.no