apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: teampensjon
  name: pensjon-kodeverk
  namespace: teampensjon
spec:
  port: 8080
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          cluster: dev-fss
          namespace: pensjon-q0
        - application: pensjon-pen-q1
          cluster: dev-fss
          namespace: pensjon-q1
        - application: pensjon-pen-q2
          cluster: dev-fss
          namespace: pensjon-q2
        - application: pensjon-pen-q5
          cluster: dev-fss
          namespace: pensjon-q5
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  ingresses:
    - https://pensjon-kodeverk.intern.dev.nav.no